import {getStore} from "@netlify/blobs";
const T=process.env.TELEGRAM_BOT_TOKEN,A=String(process.env.ADMIN_USER_ID||""),S=process.env.DATA_STORE_NAME||"gsx-check-data";
const MOMO_NAME=process.env.MOMO_NAME||"",MOMO_NUMBER=process.env.MOMO_NUMBER||"",MOMO_NETWORK=process.env.MOMO_NETWORK||"MTN";
const G=JSON.parse(process.env.GIFT_CARD_PRODUCTS_JSON||'[{"id":"us25","title":"Apple Gift Card","usd":25,"region":"US","mtcGhs":422.47},{"id":"us30","title":"Apple Gift Card","usd":30,"region":"US","mtcGhs":470.77}]');
const V=JSON.parse(process.env.VIRTUAL_NUMBER_PRODUCTS_JSON||'[{"id":"basic","title":"Virtual Number Basic","price":30,"duration":"30 days"},{"id":"plus","title":"Virtual Number Plus","price":50,"duration":"30 days"}]');
const C=["Bitcoin (BTC)","USDT — TRC20","USDT — ERC20","TRON (TRX)","Ethereum (ETH)"];
const FLAGS={USA:"🇺🇸",US:"🇺🇸",UK:"🇬🇧","UNITED KINGDOM":"🇬🇧",CANADA:"🇨🇦",GHANA:"🇬🇭",NIGERIA:"🇳🇬",KENYA:"🇰🇪",SOUTHAFRICA:"🇿🇦","SOUTH AFRICA":"🇿🇦",AUSTRALIA:"🇦🇺",GERMANY:"🇩🇪",FRANCE:"🇫🇷",SPAIN:"🇪🇸",ITALY:"🇮🇹",INDIA:"🇮🇳",JAPAN:"🇯🇵",BRAZIL:"🇧🇷",MEXICO:"🇲🇽"};
const flagFor=x=>FLAGS[String(x||"").trim().toUpperCase()]||"🌐";
const cleanCmd=(x)=>String(x||"").replace(/^\/\s*/,"").trim();
const st=()=>getStore(S), get=async(k,d=null)=>(await st().get(k,{type:"json"}))??d, put=(k,v)=>st().setJSON(k,v);
const esc=x=>String(x??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
const id=p=>p+"-"+Math.random().toString(36).slice(2,9).toUpperCase();
const money=x=>"GH₵"+Number(x).toFixed(2);
async function tg(m,b){return fetch(`https://api.telegram.org/bot${T}/${m}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)}).then(r=>r.json())}
const send=(c,t,k)=>tg("sendMessage",{chat_id:c,text:t,parse_mode:"HTML",disable_web_page_preview:true,...(k?{reply_markup:k}:{})});
const main={inline_keyboard:[
[{text:"📱 Device Check",callback_data:"device"},{text:"🌐 Website Check",callback_data:"website"}],
[{text:"🛒 Digital Store",callback_data:"store"},{text:"💳 Buy Checks",callback_data:"checks"}],
[{text:"👤 My Account",callback_data:"account"}],
[{text:"❓ Help",callback_data:"help"}]]};
const back={inline_keyboard:[[{text:"⬅️ Main Menu",callback_data:"home"}]]};
const admin={inline_keyboard:[
[{text:"💳 Payments",callback_data:"ap"},{text:"📦 Orders",callback_data:"ao"}],
[{text:"📊 Stats",callback_data:"as"},{text:"⚙️ Settings",callback_data:"aset"}]]};
async function user(m){let u=await get("u:"+m.from.id);if(!u)u={id:String(m.from.id),firstName:m.from.first_name||"",credits:0,checks:0};u.firstName=m.from.first_name||u.firstName||"";await put("u:"+u.id,u);return u}
async function order(o){await put("o:"+o.id,o);let x=await get("orders",[]);if(!x.includes(o.id)){x.push(o.id);await put("orders",x)}return o}
async function orders(){let ids=await get("orders",[]);return (await Promise.all(ids.map(x=>get("o:"+x)))).filter(Boolean)}
function websiteTypes(){return {inline_keyboard:[[{text:"🛒 E-commerce / Online Store",callback_data:"wt:E-commerce / Online Store"}],[{text:"📈 Investment / Trading",callback_data:"wt:Investment / Trading"}],[{text:"🎲 Betting / Gambling",callback_data:"wt:Betting / Gambling"}],[{text:"📱 Social Media",callback_data:"wt:Social Media"}],[{text:"💼 Job / Recruitment",callback_data:"wt:Job / Recruitment"}],[{text:"💳 Financial / Payment",callback_data:"wt:Financial / Payment"}],[{text:"🌐 Other",callback_data:"wt:Other"}],[{text:"⬅️ Main",callback_data:"home"}]]}}
function device(){return {inline_keyboard:[
[{text:"🍎 Apple IMEI",callback_data:"di:Apple"},{text:"🍎 Apple Serial",callback_data:"ds"}],
[{text:"📱 Samsung IMEI",callback_data:"di:Samsung"},{text:"🌐 Universal IMEI",callback_data:"di:Universal"}],[{text:"⬅️ Main",callback_data:"home"}]]}}
function store(){return {inline_keyboard:[[{text:"🎁 Apple Gift Cards",callback_data:"gift"},{text:"📞 Virtual Numbers",callback_data:"vn"}],[{text:"⬅️ Main",callback_data:"home"}]]}}
function checks(){return {inline_keyboard:[[{text:"1 Check — GH₵5",callback_data:"buy:1"},{text:"3 Checks — GH₵10",callback_data:"buy:3"}],[{text:"⬅️ Main",callback_data:"home"}]]}}
function pay(id){return {inline_keyboard:[[{text:"📱 MoMo",callback_data:"m:"+id},{text:"🪙 Crypto",callback_data:"c:"+id}],[{text:"❌ Cancel",callback_data:"x:"+id}]]}}
function valid(s){let x=s.replace(/\D/g,"");if(x.length!=15)return false;let z=0;for(let i=0;i<15;i++){let d=+x[i];if(i%2)d=d*2>9?d*2-9:d*2;z+=d}return z%10===0}
async function adminNotice(o,extra=""){if(!A)return;let u=await get("u:"+o.userId,{});let rows=[];
if(["momo_review","crypto_review","momo","crypto_payment"].includes(o.status)) rows.push([{text:"✅ Confirm Payment",callback_data:"confirm:"+o.id},{text:"❌ Reject",callback_data:"reject:"+o.id}]);
if(["crypto_wait"].includes(o.status)) rows.push([{text:"📤 Send Payment Details",callback_data:"adpay:"+o.id}],[{text:"❌ Reject",callback_data:"reject:"+o.id}]);
if(["paid"].includes(o.status) && ["gift","number"].includes(o.type)) rows.push([{text:"📦 Deliver",callback_data:"deliver:"+o.id},{text:"❌ Reject",callback_data:"reject:"+o.id}]);
if(["payment_method","momo"].includes(o.status) && o.type!=="checks") rows.push([{text:"❌ Reject",callback_data:"reject:"+o.id}]);
return send(A,`<b>🔔 GSX ORDER</b>\n\nOrder: <code>${o.id}</code>\nCustomer: <b>${esc(u.firstName||u.username||o.userId)}</b>\nItem: ${esc(o.item)}\nAmount: <b>${money(o.amount)}</b>\nStatus: <b>${o.status}</b>\n${extra}`,{inline_keyboard:rows});}
async function callback(q){
let c=q.message.chat.id,d=q.data,u=await get("u:"+q.from.id);await tg("answerCallbackQuery",{callback_query_id:q.id});
if(!u)return;
if(d==="home")return send(c,`<b>🛡️ GSX CHECK</b>\n\nTelegram: <b>${esc(u.firstName||"")}</b>\nChecks: <b>${u.credits}</b>\n\nMoMo sender proof is requested only during a MoMo order.\nVirtual-number country is requested only during a number order.`,main);
if(d==="website")return send(c,"<b>🌐 WEBSITE CHECK</b>\n\nFirst choose the type of website you want to verify.",websiteTypes());
if(d.startsWith("wt:")){let typ=d.slice(3);u.state={t:"website_url",siteType:typ};await put("u:"+u.id,u);return send(c,`<b>🌐 ${esc(typ)}</b>\n\nSend the website URL now.\nExample: <code>https://example.com</code>`,back);}
if(d==="device")return send(c,"<b>📱 DEVICE CHECK</b>\n\nChoose a check type.",device());
if(d==="store")return send(c,"<b>🛒 DIGITAL STORE</b>\n\nChoose a product.",store());
if(d==="checks")return send(c,"<b>💳 BUY CHECKS</b>\n\n1 check = GH₵5\n3 checks = GH₵10\n\nPayments are manually verified.",checks());
if(d==="account")return send(c,`<b>👤 ACCOUNT</b>\n\nTelegram: ${esc(u.firstName||"")}\nChecks: <b>${u.credits}</b>\nCompleted: <b>${u.checks}</b>\n\nSet/change name:\n<code>/Kofi Mensah</code>`,back);
if(d==="help")return send(c,"<b>❓ HOW IT WORKS</b>\n\n1. Choose a service.\n2. Follow the prompts.\n3. Select payment.\n4. Follow the payment instructions.\n5. Tap <b>I've Paid</b>.\n6. Admin manually verifies payment.\n7. Your result/code/number is delivered.",back);
if(d.startsWith("di:")){u.state={t:"imei",brand:d.slice(3)};await put("u:"+u.id,u);return send(c,`<b>📱 ${esc(d.slice(3))} IMEI CHECK</b>\n\nSend the 15-digit IMEI now.\n\nCommand format: <code>/imei 352851114023666</code>`,back)}
if(d==="ds"){u.state={t:"serial"};await put("u:"+u.id,u);return send(c,"<b>🍎 APPLE SERIAL CHECK</b>\n\nSend the serial number.\n\nCommand format: <code>/serial FCLD55FVN70G</code>",back)}
if(d==="gift"){let rows=G.map(p=>[{text:`US $${p.usd} — ${money(p.mtcGhs*1.17)}`,callback_data:"g:"+p.id}]);return send(c,"<b>🎁 APPLE GIFT CARDS</b>\n\nPrices are shown in USD; the exact amount to send is automatically calculated in GHS using the configured supplier price + 17% fee.",{inline_keyboard:rows.concat([[{text:"⬅️ Store",callback_data:"store"}]])})}
if(d.startsWith("g:")){let p=G.find(x=>x.id===d.slice(2));if(!p)return;let o={id:id("GSX"),userId:u.id,type:"gift",item:`US $${p.usd} Apple Gift Card`,amount:p.mtcGhs*1.17,status:"payment_method",meta:{usd:p.usd,region:p.region,base:p.mtcGhs,fee:17}};await order(o);return send(c,`<b>🎁 ${esc(o.item)}</b>\n\nSupplier price: ${money(p.mtcGhs)}\n17% fee: ${money(p.mtcGhs*.17)}\n<b>Amount to pay: ${money(o.amount)}</b>\n\nChoose payment method:`,pay(o.id))}
if(d==="vn"){let rows=V.map(p=>[{text:`📞 ${p.title} — ${money(p.price)}`,callback_data:"v:"+p.id}]);return send(c,"<b>📞 VIRTUAL NUMBERS</b>\n\nChoose a service. You will enter the country/region next.\n\n<i>Lawful use only. Use numbers only where the destination service permits VoIP/virtual numbers. No fraud, spam, impersonation or security bypass.</i>",{inline_keyboard:rows.concat([[{text:"⬅️ Store",callback_data:"store"}]])})}
if(d.startsWith("v:")){u.state={t:"country",pid:d.slice(2)};await put("u:"+u.id,u);let p=V.find(x=>x.id===d.slice(2));return send(c,`<b>📞 ${esc(p.title)}</b>\n\nPrice: <b>${money(p.price)}</b>\nDuration: ${esc(p.duration||"As listed")}\n\n<b>Step 1:</b> Reply with the country/region you need.\nExamples: <code>/🇺🇸 USA</code> or <code>/🇬🇭 Ghana</code>\nYou may also send <code>/USA</code> or <code>/Ghana</code>.`,back)}
if(d.startsWith("buy:")){let n=+d.slice(4),o={id:id("GSX"),userId:u.id,type:"checks",item:`${n} device checks`,amount:n===1?5:10,status:"payment_method",meta:{credits:n}};await order(o);return send(c,`<b>💳 CHECK PACKAGE</b>\n\n${o.item}\nAmount: <b>${money(o.amount)}</b>\n\nChoose payment method:`,pay(o.id))}
if(d.startsWith("m:")){let o=await get("o:"+d.slice(2));if(!o)return;o.status="momo";await order(o);return send(c,`<b>📱 MOMO PAYMENT</b>\n\nOrder: <code>${o.id}</code>\nSend <b>${money(o.amount)}</b> to:\n<b>${esc(MOMO_NAME)}</b>\n<b>${esc(MOMO_NUMBER)}</b>\nNetwork: ${esc(MOMO_NETWORK)}\n\nAfter paying, tap <b>I've Paid</b>.`,{inline_keyboard:[[{text:"✅ I've Paid",callback_data:"pm:"+o.id}],[{text:"❌ Cancel",callback_data:"x:"+o.id}]]})}
if(d.startsWith("pm:")){let o=await get("o:"+d.slice(3));if(!o)return;u.state={t:"sender",oid:o.id};await put("u:"+u.id,u);return send(c,"<b>🧾 PAYMENT CONFIRMATION</b>\n\nReply with the name shown on the MoMo account that sent the payment.\n\nExample:\n<code>/Kofi Mensah</code>\n\nThis is payment proof for this order, not your Telegram username.",back)}
if(d.startsWith("c:")){let o=await get("o:"+d.slice(2));if(!o)return;o.status="crypto_type";await order(o);return send(c,`<b>🪙 CRYPTO PAYMENT</b>\n\nOrder: <code>${o.id}</code>\nAmount: <b>${money(o.amount)}</b>\n\nChoose the network. The admin will manually send the address for this order.`,{inline_keyboard:C.map((x,i)=>[{text:x,callback_data:`ct:${o.id}:${i}`}])})}
if(d.startsWith("ct:")){let [_,oid,i]=d.split(":"),o=await get("o:"+oid);if(!o)return;o.status="crypto_wait";o.meta.crypto=C[+i];await order(o);await adminNotice(o,`Crypto: <b>${esc(o.meta.crypto)}</b>\n\nUse <b>Send Payment Details</b> to manually provide the address.`);return send(c,`<b>🪙 ${esc(o.meta.crypto)}</b>\n\nThe admin is preparing your payment instructions.\n<b>Do not send funds yet.</b>`,back)}
if(d.startsWith("paidc:")){let o=await get("o:"+d.slice(6));if(!o)return;o.status="crypto_review";await order(o);await adminNotice(o,`Customer says payment was sent.\nNetwork: <b>${esc(o.meta.crypto)}</b>`);return send(c,"<b>🪙 PAYMENT SUBMITTED</b>\n\nYour payment is waiting for manual verification. Please don't send another payment.",back)}
if(d.startsWith("x:")){let o=await get("o:"+d.slice(2));if(o){o.status="cancelled";await order(o)}return send(c,"❌ Order cancelled.",main)}
if(String(q.from.id)!==A)return;
if(d==="ap"){let os=(await orders()).filter(o=>!["paid","delivered","cancelled","rejected"].includes(o.status));return send(c,`<b>💳 PENDING PAYMENTS</b>\n\n${os.length?os.map(o=>`<code>${o.id}</code> — ${money(o.amount)} — ${o.status}`).join("\n"):"None"}`,admin)}
if(d==="ao"){let os=(await orders()).slice(-15).reverse();return send(c,`<b>📦 RECENT ORDERS</b>\n\n${os.length?os.map(o=>`<code>${o.id}</code> — ${esc(o.item)} — ${o.status}`).join("\n"):"None"}`,admin)}
if(d==="as"){let os=await orders(),rev=os.filter(o=>["paid","delivered"].includes(o.status)).reduce((a,o)=>a+o.amount,0);return send(c,`<b>📊 STATS</b>\n\nOrders: ${os.length}\nPaid/Delivered: ${os.filter(o=>["paid","delivered"].includes(o.status)).length}\nRecorded revenue: ${money(rev)}`,admin)}
if(d==="aset")return send(c,`<b>⚙️ SETTINGS</b>\n\nMoMo: ${esc(MOMO_NAME)} / ${esc(MOMO_NUMBER)}\nCrypto: manually supplied per order\nGift cards: ${G.length}\nVirtual-number products: ${V.length}`,admin);
if(d.startsWith("adpay:")){let o=await get("o:"+d.slice(6));let s=await get("admin:"+c,{});s={t:"paydetail",oid:o.id};await put("admin:"+c,s);return send(c,`<b>🪙 SEND PAYMENT DETAILS</b>\n\nOrder: <code>${o.id}</code>\nNetwork: <b>${esc(o.meta.crypto||"Crypto")}</b>\nAmount: <b>${money(o.amount)}</b>\n\nReply with the exact address/instructions to send to the customer.\n\nExample:\n<code>Network: TRC20\nAddress: ...\nSend exactly ${money(o.amount)}</code>`,admin)}
if(d.startsWith("deliver:")){let o=await get("o:"+d.slice(8));if(!o||o.status!=="paid")return send(c,"⚠️ Payment must be confirmed before delivery.",admin);let s=await get("admin:"+c,{});s={t:"deliver",oid:o.id};await put("admin:"+c,s);return send(c,`<b>📤 DELIVER ORDER</b>\n\nOrder: <code>${o.id}</code>\nItem: ${esc(o.item)}\n\nReply with exactly what the customer should receive.\n\nGift card: <code>XXXX-XXXX-XXXX</code>\nVirtual number: <code>Number: +1XXXXXXXXXX\nCode: 123456</code>\n\nYou can also use:\n<code>/number ORDER_ID +1XXXXXXXXXX</code>\n<code>/otp ORDER_ID 123456</code>`,admin)}
if(d.startsWith("confirm:")){let o=await get("o:"+d.slice(8));if(!o)return;if(["paid","delivered","rejected"].includes(o.status))return send(c,"Already processed.",admin);o.status="paid";await order(o);if(o.type==="checks"){let cu=await get("u:"+o.userId,{});cu.credits=(cu.credits||0)+(o.meta.credits||0);await put("u:"+cu.id,cu);await send(o.userId,`<b>✅ PAYMENT CONFIRMED</b>\n\n${esc(o.item)} added.\nChecks available: <b>${cu.credits}</b>`,main)}else await send(o.userId,`<b>✅ PAYMENT CONFIRMED</b>\n\nOrder: <code>${o.id}</code>\n${esc(o.item)}\n\nYour payment has been verified. Fulfillment is being prepared.`,main);return send(c,"✅ Payment confirmed.",admin)}
if(d.startsWith("reject:")){let o=await get("o:"+d.slice(7));o.status="rejected";await order(o);await send(o.userId,`❌ Payment was not confirmed for order <code>${o.id}</code>.`,main);return send(c,"Rejected.",admin)}
}
async function text(m,u){
let c=m.chat.id,t=(m.text||"").trim();

// Customer-facing service commands. These are state-specific so /Kofi Mensah is
// only treated as MoMo proof during a MoMo payment, and /USA is only treated as
// a country during a virtual-number order.
if(u.state?.t==="sender"){let raw=cleanCmd(t);if(!raw||raw.length<2)return send(c,"❌ Please enter the MoMo account name. Example: <code>/Kofi Mensah</code>",back);let o=await get("o:"+u.state.oid);if(!o)return; o.status="momo_review";o.meta.sender=raw;u.state=null;await put("u:"+u.id,u);await order(o);await adminNotice(o,`MoMo sender/account name: <b>${esc(raw)}</b>`);return send(c,`<b>🧾 PAYMENT SUBMITTED</b>\n\nOrder: <code>${o.id}</code>\nMoMo sender: <b>${esc(raw)}</b>\n\nWaiting for manual verification.`,back)}
if(u.state?.t==="country"){let raw=cleanCmd(t).replace(/^[^A-Za-z]+/g,"").trim();if(!raw)return send(c,"❌ Please enter a country/region. Examples: <code>/🇺🇸 USA</code> or <code>/🇬🇭 Ghana</code>\nYou may also send <code>/USA</code> or <code>/Ghana</code>.",back);let p=V.find(x=>x.id===u.state.pid);if(!p)return;let o={id:id("GSX"),userId:u.id,type:"number",item:p.title,amount:p.price,status:"payment_method",meta:{country:raw,duration:p.duration}};u.state=null;await put("u:"+u.id,u);await order(o);await adminNotice(o,"New virtual-number order awaiting payment selection.");return send(c,`<b>📞 VIRTUAL NUMBER ORDER</b>\n\nProduct: ${esc(p.title)}\nCountry/region: <b>${flagFor(raw)} ${esc(raw)}</b>\nDuration: ${esc(p.duration)}\nAmount: <b>${money(p.price)}</b>\n\nChoose payment:`,pay(o.id))}
if(/^\/imei\s+/i.test(t)){let value=t.replace(/^\/imei\s+/i,"").trim();if(!valid(value))return send(c,"❌ Invalid IMEI. Use: <code>/imei 352851114023666</code>",back);if(u.credits<1)return send(c,"⚠️ You have no checks. Buy credits first.",checks());u.credits--;u.checks++;await put("u:"+u.id,u);return send(c,`<b>📱 GSX CHECK REPORT</b>\n\nIMEI: •••••••••••${esc(value.slice(-4))}\nStatus: <b>NOT VERIFIED</b>\nBlacklist: <b>UNKNOWN</b>\nActivation Lock: <b>UNKNOWN</b>\nSIM Lock: <b>UNKNOWN</b>\nCarrier: <b>UNKNOWN</b>\n\n<i>Provider-backed results require an authorized API.</i>`,main)}
if(/^\/serial\s+/i.test(t)){let value=t.replace(/^\/serial\s+/i,"").trim();if(value.length<4||value.length>32)return send(c,"❌ Invalid serial. Use: <code>/serial FCLD55FVN70G</code>",back);if(u.credits<1)return send(c,"⚠️ You have no checks. Buy credits first.",checks());u.credits--;u.checks++;await put("u:"+u.id,u);return send(c,`<b>🍎 APPLE SERIAL REPORT</b>\n\nSerial: <code>${esc(value)}</code>\nStatus: <b>NOT VERIFIED</b>\n\n<i>Real provider data will be added through the authorized API adapter.</i>`,main)}

if(/^\/help\s+numbers?/i.test(t)){return send(c,"<b>📞 NUMBER DELIVERY COMMANDS</b>\n\nAdmin can deliver a purchased number with the order command.\nCustomer will receive the number and, when applicable, an incoming verification message from the provider.\n\n<i>Use only for lawful services that permit virtual numbers.</i>",back)}

if(u.state?.t==="website_url"){let url=t.trim();if(!/^https?:\/\//i.test(url))url="https://"+url;if(!/^https?:\/\/[^\s]+$/i.test(url))return send(c,"❌ Invalid URL. Example: <code>https://example.com</code>",back);if(u.credits<1)return send(c,"⚠️ You have no checks. Buy credits first.",checks());let siteType=u.state.siteType;u.state=null;u.credits--;u.checks++;await put("u:"+u.id,u);let o={id:id("WEB"),userId:u.id,type:"website",item:`Website Check — ${siteType}`,amount:0,status:"completed",meta:{siteType,url}};await order(o);return send(c,`<b>🌐 WEBSITE CHECK REQUEST</b>\n\nType: <b>${esc(siteType)}</b>\nURL: <code>${esc(url)}</code>\nCheck ID: <code>${o.id}</code>\nStatus: <b>NOT VERIFIED</b>\n\nBlacklist/risk results are only shown when an authorized provider is connected.`,main)}
let as=String(c)===A?await get("admin:"+c,{}):{};
if(String(c)===A&&/^\/deliver\s+/i.test(t)){let m=t.match(/^\/deliver\s+(\S+)(?:\s+([\s\S]+))?$/i);let oid=m?.[1],payload=m?.[2];let o=oid?await get("o:"+oid):null;if(!o)return send(c,"❌ Order not found. Use: <code>/deliver GSX-XXXXXX</code>",admin);if(o.status!=="paid")return send(c,"⚠️ Payment must be confirmed before delivery.",admin);if(!payload){as={t:"deliver",oid:o.id};await put("admin:"+c,as);return send(c,`<b>📦 DELIVER</b>\n\nOrder: <code>${o.id}</code>\nItem: ${esc(o.item)}\n\nReply with the delivery content.\n\nFor a virtual number, use:\n<code>Number: +1XXXXXXXXXX\nCode: 123456</code>`,admin)}o.status="delivered";o.meta.deliveredAt=new Date().toISOString();await order(o);await send(o.userId,`<b>📦 ORDER DELIVERED</b>\n\nOrder: <code>${o.id}</code>\n${esc(o.item)}\n\n<pre>${esc(payload)}</pre>`,main);return send(c,"✅ Delivered.",admin)}
if(String(c)===A&&/^\/number\s+/i.test(t)){let m=t.match(/^\/number\s+(\S+)\s+([\s\S]+)$/i),oid=m?.[1],num=m?.[2];let o=oid?await get("o:"+oid):null;if(!o||o.type!=="number")return send(c,"❌ Use: <code>/number ORDER_ID +123456789</code>",admin);if(o.status!=="paid")return send(c,"⚠️ Confirm payment first.",admin);o.meta.number=num;await order(o);await send(o.userId,`<b>📞 YOUR NUMBER IS READY</b>\n\nOrder: <code>${o.id}</code>\nCountry: ${flagFor(o.meta.country)} ${esc(o.meta.country)}\nNumber: <code>${esc(num)}</code>\n\nWaiting for the provider message/code if applicable.`,main);return send(c,"✅ Number sent to customer.",admin)}
if(String(c)===A&&/^\/otp\s+/i.test(t)){let m=t.match(/^\/otp\s+(\S+)\s+(.+)$/i),oid=m?.[1],code=m?.[2];let o=oid?await get("o:"+oid):null;if(!o||o.type!=="number")return send(c,"❌ Use: <code>/otp ORDER_ID 123456</code>",admin);if(o.status!=="paid")return send(c,"⚠️ Confirm payment first.",admin);o.meta.otp=code;await order(o);await send(o.userId,`<b>🔐 VERIFICATION CODE RECEIVED</b>\n\nOrder: <code>${o.id}</code>\nCode: <code>${esc(code)}</code>\n\n<i>Use this only where the destination service permits third-party/virtual numbers.</i>`,main);return send(c,"✅ Code sent to customer.",admin)}
if(String(c)===A&&/^\/proof\s+/i.test(t)){let m=t.match(/^\/proof\s+(\S+)\s+([\s\S]+)$/i),oid=m?.[1],proof=m?.[2];let o=oid?await get("o:"+oid):null;if(!o)return send(c,"❌ Use: <code>/proof ORDER_ID proof-details</code>",admin);o.meta.proof=proof;await order(o);return send(c,"✅ Proof attached to order.",admin)}
if(String(c)===A&&as?.t==="paydetail"){let o=await get("o:"+as.oid);o.status="crypto_payment";o.meta.instructions=t;await order(o);await put("admin:"+c,{});return send(o.userId,`<b>🪙 PAYMENT INSTRUCTIONS</b>\n\nOrder: <code>${o.id}</code>\nAmount: <b>${money(o.amount)}</b>\nNetwork: <b>${esc(o.meta.crypto)}</b>\n\n<pre>${esc(t)}</pre>\n\nAfter paying, tap <b>I've Paid</b>.`,{inline_keyboard:[[{text:"✅ I've Paid",callback_data:"paidc:"+o.id}]]})}
if(String(c)===A&&as?.t==="deliver"){let o=await get("o:"+as.oid);o.status="delivered";o.meta.deliveredAt=new Date().toISOString();await order(o);await put("admin:"+c,{});await send(o.userId,`<b>📦 ORDER DELIVERED</b>\n\nOrder: <code>${o.id}</code>\nItem: <b>${esc(o.item)}</b>\n\n<pre>${esc(t)}</pre>`,main);return send(c,"✅ Delivered.",admin)}
if(u.state?.t==="imei"){let brand=u.state.brand;u.state=null;await put("u:"+u.id,u);if(!valid(t))return send(c,"❌ Invalid IMEI. Send the 15-digit IMEI again.",back);if(u.credits<1)return send(c,"⚠️ You have no checks. Buy credits first.",checks());u.credits--;u.checks++;await put("u:"+u.id,u);return send(c,`<b>📱 GSX CHECK REPORT</b>\n\nStatus: <b>NOT VERIFIED</b>\nBrand: ${esc(brand)}\nIMEI: •••••••••••${t.slice(-4)}\nBlacklist: <b>UNKNOWN</b>\nActivation Lock: <b>UNKNOWN</b>\nSIM Lock: <b>UNKNOWN</b>\nCarrier: <b>UNKNOWN</b>\n\n<i>No provider-backed result is claimed until an authorized API is connected.</i>`,main)}
if(u.state?.t==="serial"){u.state=null;await put("u:"+u.id,u);if(u.credits<1)return send(c,"⚠️ You have no checks. Buy credits first.",checks());u.credits--;u.checks++;await put("u:"+u.id,u);return send(c,`<b>🍎 APPLE SERIAL REPORT</b>\n\nSerial: <code>${esc(t)}</code>\nStatus: <b>NOT VERIFIED</b>\n\n<i>Real provider data will be added through the authorized API adapter.</i>`,main)}
if(t==="/start"||t==="/help")return send(c,`<b>🛡️ GSX CHECK</b>\n\nTelegram: <b>${esc(u.firstName||"")}</b>\nChecks: <b>${u.credits}</b>\n\nMoMo sender proof is requested only during a MoMo order.\nVirtual-number country is requested only during a number order.`,main);
if(t==="/admin"&&String(c)===A)return send(c,"<b>🛡️ ADMIN PANEL</b>\n\n<b>Delivery commands</b>\n<code>/deliver ORDER_ID</code> — open delivery prompt\n<code>/deliver ORDER_ID CONTENT</code> — deliver directly\n<code>/number ORDER_ID +123456789</code> — send virtual number\n<code>/otp ORDER_ID 123456</code> — send verification code\n<code>/proof ORDER_ID DETAILS</code> — attach proof\n\n<b>Customer commands</b>\n<code>/imei 15_DIGITS</code>\n<code>/serial SERIAL</code>\n<code>/Kofi Mensah</code> — only when MoMo asks for sender name\n<code>/USA</code> — only when a number order asks for country",admin);
if(t==="/pending"&&String(c)===A)return callback({message:{chat:{id:c}},data:"ap",from:m.from,id:"x"});
return send(c,"Use the buttons below, or set your name like:\n<code>/Kofi Mensah</code>",main)}
export default async req=>{try{if(req.method==="GET")return new Response("GSX CHECK is online.");let x=await req.json();if(x.callback_query)await callback(x.callback_query);else if(x.message)await text(x.message,await user(x.message));return new Response("ok")}catch(e){console.error(e);return new Response("GSX CHECK error",{status:500})}};
